  
name: Waka Readme

on:
  schedule:
    # Runs at 1:25am IST
    - cron: '55 19 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: proRamLOGO
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_TIMEZONE: False
          SHOW_COMMIT: True
          SHOW_LANGUAGE: False
          SHOW_LINES_OF_CODE: True
